#*************************************************************************************************
#
#        Heidelberg University - PCA Exercise 03
#
#                            Group : PCA03
#		       Participant : Klaus Naumann
#				     Jan Brodhaecker  
#
#                            File : nbody.h
#
#                         Purpose : N-Body Simulation (2D)
#
#*************************************************************************************************
 
CPP=g++
CFLAGS = -Wall

nbody :
	$(CPP) $(CFLAGS)	src/main.cpp \
				src/nbody.cpp \
				-o nbody

clean :
	rm -f nbody
